### ISSUE TITLE
potential conflict in the delete-stacks branch

### ISSUE THREAD

**Issue by ironmanwaring** [sweetskills/lambda-functions#12]
@paulSambolin just saw the delete-stacks function - was it intended to fit the same purpose as destroy-stacks (be used for an auto delete) or for something else?

if same thing, i'll remove the delete-stacks

**Comment by paulSambolin** [comment]
No, it is not an auto delete.  I was  manually running it to delete all the stacks.

**Comment by ironmanwaring** [comment]
do you want me to keep it?

**Comment by paulSambolin** [comment]
Not necessary if we have a better function for auto deleting
